name: shared_preferences_plus
description: "A Flutter plugin for reading and writing key-value pairs with named containers."
version: 1.0.0
homepage: https://github.com/sanjeev2552/shared_preferences_plus
repository: https://github.com/sanjeev2552/shared_preferences_plus
issue_tracker: https://github.com/sanjeev2552/shared_preferences_plus/issues

environment:
  sdk: ^3.11.1
  flutter: ">=3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: shared_preferences_plus_android
      ios:
        default_package: shared_preferences_plus_foundation
      linux:
        default_package: shared_preferences_plus_linux
      macos:
        default_package: shared_preferences_plus_foundation
      web:
        default_package: shared_preferences_plus_web
      windows:
        default_package: shared_preferences_plus_windows

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_plus_android: ^1.0.0
  shared_preferences_plus_foundation: ^1.0.0
  shared_preferences_plus_linux: ^1.0.0
  shared_preferences_plus_web: ^1.0.0
  shared_preferences_plus_windows: ^1.0.0
  shared_preferences_plus_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
