name: shared_preferences_plus_windows
description: "Windows implementation of shared_preferences_plus."
version: 1.0.0
homepage: https://github.com/sanjeev2552/shared_preferences_plus
repository: https://github.com/sanjeev2552/shared_preferences_plus
issue_tracker: https://github.com/sanjeev2552/shared_preferences_plus/issues

environment:
  sdk: ^3.11.1
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: shared_preferences_plus
    platforms:
      windows:
        dartPluginClass: SharedPreferencesPlusWindows

dependencies:
  file: ^7.0.1
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider_windows: ^2.3.0
  shared_preferences_plus_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
