// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct SharedPreferencesPlusPigeonOptions: Hashable {
  var name: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SharedPreferencesPlusPigeonOptions? {
    let name = pigeonVar_list[0] as! String

    return SharedPreferencesPlusPigeonOptions(
      name: name
    )
  }
  func toList() -> [Any?] {
    return [
      name
    ]
  }
  static func == (lhs: SharedPreferencesPlusPigeonOptions, rhs: SharedPreferencesPlusPigeonOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return SharedPreferencesPlusPigeonOptions.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SharedPreferencesPlusPigeonOptions {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SharedPreferencesPlusApi {
  func setString(key: String, value: String, options: SharedPreferencesPlusPigeonOptions) throws
  func getString(key: String, options: SharedPreferencesPlusPigeonOptions) throws -> String?
  func setInt(key: String, value: Int64, options: SharedPreferencesPlusPigeonOptions) throws
  func getInt(key: String, options: SharedPreferencesPlusPigeonOptions) throws -> Int64?
  func setDouble(key: String, value: Double, options: SharedPreferencesPlusPigeonOptions) throws
  func getDouble(key: String, options: SharedPreferencesPlusPigeonOptions) throws -> Double?
  func setBool(key: String, value: Bool, options: SharedPreferencesPlusPigeonOptions) throws
  func getBool(key: String, options: SharedPreferencesPlusPigeonOptions) throws -> Bool?
  func setStringList(key: String, value: [String], options: SharedPreferencesPlusPigeonOptions) throws
  func getStringList(key: String, options: SharedPreferencesPlusPigeonOptions) throws -> [String]?
  func remove(key: String, options: SharedPreferencesPlusPigeonOptions) throws
  func clear(options: SharedPreferencesPlusPigeonOptions) throws
  func containsKey(key: String, options: SharedPreferencesPlusPigeonOptions) throws -> Bool
  func getKeys(options: SharedPreferencesPlusPigeonOptions) throws -> [String]
  func getAll(options: SharedPreferencesPlusPigeonOptions) throws -> [String: Any?]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SharedPreferencesPlusApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `SharedPreferencesPlusApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SharedPreferencesPlusApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.setString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        let optionsArg = args[2] as! SharedPreferencesPlusPigeonOptions
        do {
          try api.setString(key: keyArg, value: valueArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setStringChannel.setMessageHandler(nil)
    }
    let getStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.getString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let optionsArg = args[1] as! SharedPreferencesPlusPigeonOptions
        do {
          let result = try api.getString(key: keyArg, options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStringChannel.setMessageHandler(nil)
    }
    let setIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.setInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Int64
        let optionsArg = args[2] as! SharedPreferencesPlusPigeonOptions
        do {
          try api.setInt(key: keyArg, value: valueArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setIntChannel.setMessageHandler(nil)
    }
    let getIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.getInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let optionsArg = args[1] as! SharedPreferencesPlusPigeonOptions
        do {
          let result = try api.getInt(key: keyArg, options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getIntChannel.setMessageHandler(nil)
    }
    let setDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.setDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Double
        let optionsArg = args[2] as! SharedPreferencesPlusPigeonOptions
        do {
          try api.setDouble(key: keyArg, value: valueArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDoubleChannel.setMessageHandler(nil)
    }
    let getDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.getDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let optionsArg = args[1] as! SharedPreferencesPlusPigeonOptions
        do {
          let result = try api.getDouble(key: keyArg, options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDoubleChannel.setMessageHandler(nil)
    }
    let setBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.setBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Bool
        let optionsArg = args[2] as! SharedPreferencesPlusPigeonOptions
        do {
          try api.setBool(key: keyArg, value: valueArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBoolChannel.setMessageHandler(nil)
    }
    let getBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.getBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let optionsArg = args[1] as! SharedPreferencesPlusPigeonOptions
        do {
          let result = try api.getBool(key: keyArg, options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBoolChannel.setMessageHandler(nil)
    }
    let setStringListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.setStringList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStringListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! [String]
        let optionsArg = args[2] as! SharedPreferencesPlusPigeonOptions
        do {
          try api.setStringList(key: keyArg, value: valueArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setStringListChannel.setMessageHandler(nil)
    }
    let getStringListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.getStringList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStringListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let optionsArg = args[1] as! SharedPreferencesPlusPigeonOptions
        do {
          let result = try api.getStringList(key: keyArg, options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getStringListChannel.setMessageHandler(nil)
    }
    let removeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.remove\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let optionsArg = args[1] as! SharedPreferencesPlusPigeonOptions
        do {
          try api.remove(key: keyArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeChannel.setMessageHandler(nil)
    }
    let clearChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.clear\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! SharedPreferencesPlusPigeonOptions
        do {
          try api.clear(options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearChannel.setMessageHandler(nil)
    }
    let containsKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.containsKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      containsKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let optionsArg = args[1] as! SharedPreferencesPlusPigeonOptions
        do {
          let result = try api.containsKey(key: keyArg, options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      containsKeyChannel.setMessageHandler(nil)
    }
    let getKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.getKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! SharedPreferencesPlusPigeonOptions
        do {
          let result = try api.getKeys(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getKeysChannel.setMessageHandler(nil)
    }
    let getAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_preferences_plus_android.SharedPreferencesPlusApi.getAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! SharedPreferencesPlusPigeonOptions
        do {
          let result = try api.getAll(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAllChannel.setMessageHandler(nil)
    }
  }
}
