name: shared_preferences_plus_platform_interface
description: "Platform interface for shared_preferences_plus."
version: 1.0.0
homepage: https://github.com/sanjeev2552/shared_preferences_plus
repository: https://github.com/sanjeev2552/shared_preferences_plus
issue_tracker: https://github.com/sanjeev2552/shared_preferences_plus/issues

environment:
  sdk: ^3.11.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
