name: shared_preferences_plus_foundation
description: "iOS and macOS implementation of shared_preferences_plus."
version: 1.0.6
homepage: https://github.com/sanjeev2552/shared_preferences_plus
repository: https://github.com/sanjeev2552/shared_preferences_plus
issue_tracker: https://github.com/sanjeev2552/shared_preferences_plus/issues

environment:
  sdk: ^3.11.1
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: shared_preferences_plus
    platforms:
      ios:
        pluginClass: SharedPreferencesPlusFoundationPlugin
        dartPluginClass: SharedPreferencesPlusFoundation
        sharedDarwinSource: true
      macos:
        pluginClass: SharedPreferencesPlusFoundationPlugin
        dartPluginClass: SharedPreferencesPlusFoundation
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_plus_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.2.3
